name: Build and deploy Next.js app to Azure Web App - app-step4-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      # ビルド前に必ず .env.local を書き出す
      - name: Create .env.local
        run: echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.local

      # 本当に書き込まれているか直前で確認
      - name: Check .env.local
        run: cat .env.local

      # ここで “DEBUG:” を必ず出力させ、かつ env: で渡す
      - name: Build Next.js app
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          echo "### DEBUG: NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"
          npm run build

      # 古い静的ファイル(out/)が残っていると nextExport を優先してしまうので物理削除
      - name: Remove legacy export folder
        run: rm -rf out export-marker.json *.html || true

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          cp -r .next/standalone/* deploy/
          [ -d ".next/static" ] && cp -r .next/static deploy/.next/static || echo "skip static"
          [ -d "public" ] && cp -r public deploy/public || echo "skip public"
          cp next.config.js deploy/
          zip -r release.zip deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-step4-1
          slot-name: Production
          package: ./deploy
          publish-profile: ${{ secrets.POS4 }}
