name: Build and deploy Next.js app to Azure Web App - app-step4-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r .next deploy/.next
          cp -r node_modules deploy/node_modules
          cp package.json deploy/
          cp next.config.js deploy/ 2>/dev/null || echo "next.config.js not found, skipping"
          zip -r release.zip deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Debug - Check files and secrets
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Files in deploy directory:"
          ls -la deploy/
          echo "Checking publish profile secret (first 50 chars):"
          echo "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_POS4 }}" | head -c 50
        env:
          PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_POS4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-step4-1'
          slot-name: 'Production'
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_POS4 }}