name: Build and deploy Next.js app to Azure Web App - app-step4-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Create deployment package
        run: |
          echo "=== Creating deployment package ==="
          mkdir deploy
          
          # Copy built Next.js files
          cp -r .next deploy/.next
          
          # Copy node_modules (required for Next.js runtime)
          cp -r node_modules deploy/node_modules
          
          # Copy package files
          cp package.json deploy/
          cp package-lock.json deploy/ 2>/dev/null || echo "No package-lock.json found"
          
          # Copy Next.js config if exists
          cp next.config.js deploy/ 2>/dev/null || echo "No next.config.js found"
          
          # Copy pages directory (source files needed for dynamic routing)
          cp -r pages deploy/pages
          
          # Copy public directory if exists
          if [ -d "public" ]; then
            cp -r public deploy/public
            echo "Public directory copied"
          else
            echo "No public directory found"
          fi
          
          echo "=== Deployment package contents ==="
          ls -la deploy/
          
          # Create zip file
          cd deploy && zip -r ../release.zip . && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Debug - Verify deployment structure
        run: |
          echo "=== Root directory contents ==="
          ls -la
          echo ""
          echo "=== Package.json content ==="
          cat package.json
          echo ""
          echo "=== Next.js build verification ==="
          ls -la .next/ 2>/dev/null || echo "No .next directory"
          echo ""
          echo "=== Pages directory ==="
          ls -la pages/ 2>/dev/null || echo "No pages directory"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-step4-1'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_POS4 }}
          package: .