name: Build and deploy Next.js app to Azure Web App - app-step4-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js をセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. 依存パッケージをインストール
      - name: Install dependencies
        run: npm ci

      # 4. ビルド時に環境変数を渡して Next.js をビルド
      - name: Build Next.js app
        run: |
          echo "### DEBUG: NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"
          NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL }}" npm run build
        # env をここに書くと echo でも渡っているか見やすい
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      # 5. 出力された standalone モードの成果物をまとめる
      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          cp -r .next/standalone/* deploy/
          [ -d ".next/static" ] && cp -r .next/static deploy/.next/static || echo "No .next/static"
          [ -d "public" ]      && cp -r public deploy/public || echo "No public"
          cp next.config.js deploy/
          zip -r release.zip deploy

      # 6. Azure 用に ZIP 化した成果物をアップロード
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      # 7. Azure Web App へデプロイ
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-step4-1'                 # ← Azure ポータルで確認した App Service 名
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.POS4 }}    # ← GitHub Secrets に登録した発行プロファイル

